version: '3.8'

services:

  # mongo_db:
  #   container_name: db_container
  #   image: mongo:latest
  #   restart: always
  #   volumes:
  #     - mongo_db:/data/db
  #   ports:
  #     - "27017:27017"
  api:
    build: .
    ports:
      - 8002:8002
      - 27017:27017
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    # depends_on:
    #   - mongo_db

volumes:
  mongo_db: {}
